[theme]
base = "dark"
primaryColor = "#6B6B6B"
backgroundColor = "#000000"
secondaryBackgroundColor = "#212121"
textColor = "#ECECEC"
borderColor = "#3F3F46"
font = "sans serif"
baseRadius = "full"
buttonRadius = "full"
showWidgetBorder = false
showSidebarBorder = false

[client]
toolbarMode = "minimal"
